### ISSUE TITLE
ModuleNotFoundError: No module named 'modeling_telechat_gptq'

### ISSUE THREAD

**Issue by zhanghui-china** [Tele-AI/Telechat#11]
from modeling_telechat_gptq import TelechatGPTQForCausalLM
ModuleNotFoundError: No module named 'modeling_telechat_gptq'

where is TelechatGPTQForCausalLM?

**Comment by liuxz0801** [comment]
[quant/ #](https://github.com/Tele-AI/Telechat/blob/0ade229ebc64b32d531e68232b3b7deafcb35aeb/quant/modeling_telechat_gptq.py#L19C7-L19C30)
the class telechatGPTQForCausalLM is here.

**Comment by zhanghui-china** [comment]
看到了。谢谢。
