### ISSUE TITLE
镜像下载链接好像有误

### ISSUE THREAD

**Issue by 768761418** [Tele-AI/Telechat#20]
我想尝试部署web端的镜像，但是我尝试下载web端的镜像的时候提示“抱歉，您访问的页面地址有误，或者该页面不存在”

**Comment by liuxz0801** [comment]
感谢提醒，已经修改更新

**Comment by 768761418** [comment]
我尝试使用您更新的新链接下载镜像，但是还是出现位置，我查看了网络请求返回为ShareInfoNotFound，我猜测有没有可能是被认定为奇怪的东西被云盘给和谐了
![Uploading shareInfoNotFound.png…]()

**Comment by 768761418** [comment]
![shareInfoNotFound](https://github.com/Tele-AI/Telechat/assets/78351032/4bec1096-1c74-4e7b-9873-d4fe134ebdc8)
