### ISSUE TITLE
vllm推理或者符合open-Ai格式的API服务可以支持吗？

### ISSUE THREAD

**Issue by Moon502** [Tele-AI/Telechat#49]

**Comment by shunxing12345** [comment]
vllm 现在已经支撑telechat12b 可以试一下https://github.com/Tele-AI/Telechat/tree/master/service/vllm_inf

**Comment by hv0905** [comment]
> vllm 现在已经支撑telechat12b 可以试一下https://github.com/Tele-AI/Telechat/tree/master/service/vllm_inf

@shunxing12345 请问vllm推理的`TeleChat12BForCausalLM`提供除了12B外其它权重模型的开箱即用支持吗？还是仅支持12B模型的部署

**Comment by shunxing12345** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
