### ISSUE TITLE
lora微调1B结果有问题

### ISSUE THREAD

**Issue by lichengyang666** [Tele-AI/Telechat#54]

**Comment by lichengyang666** [comment]
由于资源问题选择了telechat 1B模型，全量参数跑了结果没有问题，尝试了一下lora微调，训练过程中loss也在正常下降，跟全量loss下降趋势差不多，但是最后保存的模型测试结果生成基本都是<bot>，这是什么原因呢，是不是lora模型转换和保存这块有点问题

**Comment by lichengyang666** [comment]
所以想问一下 1B是否能够支持lora微调呢？

**Comment by LSX-Sneakerprogrammer** [comment]
目前还没有适配1b模型的lora微调，后续会进行适配

**Comment by lichengyang666** [comment]
> 目前还没有适配1b模型的lora微调，后续会进行适配

好的，十分感谢~希望能够尽快适配
