### ISSUE TITLE
是否支持Agent

### ISSUE THREAD

**Issue by zhanpengjie** [Tele-AI/Telechat#58]
请问telechat支持agent吗，可否开源相关代码

**Comment by shunxing12345** [comment]
暂时还不支持agent

**Comment by wkkkkkkkm** [comment]
@shunxing12345 不是有一个开源的telechat_12B_v2_2_0629版本吗，这个好像是具备一定的function call能力的。在huggingface都没看到。

**Comment by shunxing12345** [comment]
支持function calling还在测试中 之后会有计划开源
